# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# User specific aliases and functions

## Aliases
alias ls='ls --color=auto'
alias update='yay -Syy'
alias upgrade='yay -Syu'
alias install='yay -S'
alias remove='yay -Rns'
alias search='yay'

## Terminal prompt
PS1='\W > '

## Defaults
export EDITOR='vim'
export VISUAL='vim'
