# @summary A short summary of the purpose of this class
#
# A description of what this class does
#
# @example
#   include software
class software {
  include software::teamviewer
  include software::spotify
  include software::darktable
  include software::gimp
  include software::vlc
  include software::steam
  include software::mega
  include software::cmake
  include software::oomox
  include software::gotop
  include software::palemoon
  include software::vibrancyicons
  include software::wallpapersjuhraya
  include software::deluge
  include software::zsh
  include software::hexchat
  include software::screenfetch
  include software::speedtest
  include software::moc
  include software::firefox
  include software::signal
  include software::tuxedocontrolcenter
  include software::discord
  include software::libreoffice
  include software::greenwithenvy
  include software::rofi
  include software::instawow
  include software::redshift
  include software::iosevka
  include software::dejavu
  include software::lutris
  include software::neofetch
  include software::onlyoffice
  include software::pacwall
  include software::transmission
  include software::tlp
  include software::spicetify
  include software::timeshift
  include software::vscode
  include software::paprefs
  include software::mpv
  include software::packsize
  include software::spectrwm
  include software::dunst
  include software::cron
  include software::dmenu
  include software::arandr
  include software::pcmanfm
  include software::lxappearence
  include software::weechat
  include software::gparted
  include software::akm
  include software::wps
  include software::telegram
  include software::go
  include software::rust
  include software::noto
  include software::arc
  include software::foomatic
  include software::capitaine
  include software::hplip
  include software::gutenprint
  include software::kio
  include software::doxygen
  include software::qt5
  include software::glmark2
  include software::vala
  include software::gtop
  include software::modemmanager
  include software::glances
  include software::gnu
  include software::printer
  include software::croscore
  include software::mplayer
  include software::swig
  include software::liberation
  include software::ubuntu
  include software::fileroller
  include software::carlito
  include software::paper
  include software::libqmi
  include software::nodejs
  include software::gnome
  include software::lirc
  include software::parallel
  include software::openconnect
  include software::kde
  include software::xfce4
  include software::caladea
  include software::leafpad
  include software::welcome
  include software::nano
  include software::blueberry
  include software::networkmanager
  include software::xterm
  include software::endeavour
  include software::kernel
  include software::bind
  include software::onefetch
  include software::libpdfium
  include software::gn
  include software::linux
  include software::galculator
  include software::drivers
  include software::mail
  include software::lightdm
  include software::dns
  include software::picom
  include software::benchmark
  include software::scripts
}
